<% local_config = File.join(Rails.root, 'config/app_config_local.yml') %>
<% if File.exists?(local_config) %>
<%= File.open(local_config).read %>
<% else %>
local_config: &local_config
  nothing: here
<% end %>

shared_config: &shared_config
  email_name: MTWA WebBot
  email_address: mtwaweb@gmail.com
  email_domain: mtwa.heroku.com
  email_password: <%= ENV['email_password'] %>
  local_hostname: mtwa.local
  production_hostname: mtwa.heroku.com

development:
  <<: *local_config
  <<: *shared_config
  contact_us_recipients: heedspin@gmail.com
  
production:
  <<: *local_config
  <<: *shared_config
  contact_us_recipients: heedspin@gmail.com
  rturk_access_key_id: ENV['rturk_access']
  rturk_secret_access_key: ENV['rturk_secret']
  
test:
  <<: *local_config
  <<: *shared_config

