<% appname = DEFINE_ME %>
development:
  encoding: utf8
  adapter: mysql
  database: <%= appname %>_development
  username: root
  host: 127.0.0.1
  pool: 5
  timeout: 5000

test:
  encoding: utf8
  adapter: mysql
  database: <%= appname %>_test
  pool: 5
  timeout: 5000
